"use client";

import { useState } from "react";

import { DashboardShell } from "../../components/dashboard-shell";
import { StateBlock } from "../../components/status";
import { workerApiPaths } from "../../lib/dashboard-data";
import { workerApiUrl } from "../../lib/api";

export default function ExportPage() {
  const [dataset, setDataset] = useState("sellers");
  const exportUrl = workerApiUrl(`${workerApiPaths.export}?dataset=${dataset}`);

  return (
    <DashboardShell active="export" eyebrow="Export" title="CSV Export">
      <form className="toolbar" aria-label="Export options">
        <label>
          Dataset
          <select onChange={(event) => setDataset(event.target.value)} value={dataset}>
            <option value="sellers">Sellers</option>
            <option value="contacts">Masked contacts</option>
            <option value="crawls">Crawl runs</option>
          </select>
        </label>
        <a className="button-link" href={exportUrl}>Download CSV</a>
      </form>
      <StateBlock
        title="Private Export"
        detail="Exports are generated by the authenticated Worker and limited to 1,000 rows. Crawl runs include operational status and bounded result counts. Contact values remain masked and suppressed records are excluded."
      />
    </DashboardShell>
  );
}
